server.port=${PORT:8081}

spring.application.name=myproject1

# # H2 Database Configuration (for local development)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# # H2 Console Configuration
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# PostgreSQL Database Configuration (commented out for now)
spring.datasource.url=jdbc:postgresql://dpg-d6g1sbjuibrs739e04lg-a/demo_hixu
spring.datasource.username=demo_kzas_user
spring.datasource.password=zNpvIgktX3pS0AtrmE7ovBXI48QYs1HA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# # H2 Console Configuration
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
